"""Backend boundary used by the MCP layer."""

from __future__ import annotations

from typing import Protocol

from models import MTFRequest, OptimizationRequest, SingletSpec, SpotRequest, SystemConfiguration


class OpticStudioBackend(Protocol):
    def health_check(self) -> dict: ...
    def new_sequential_system(self) -> dict: ...
    def create_singlet(self, spec: SingletSpec) -> dict: ...
    def set_system_configuration(self, config: SystemConfiguration) -> dict: ...
    def quick_focus_preview(self) -> dict: ...
    def apply_quick_focus(self) -> dict: ...
    def get_paraxial_summary(self) -> dict: ...
    def spot_diagram(self, request: SpotRequest) -> dict: ...
    def mtf(self, request: MTFRequest) -> dict: ...
    def preview_optimization(self, request: OptimizationRequest) -> dict: ...
    def run_optimization(self, request: OptimizationRequest) -> dict: ...
    def preview_save(self, relative_path: str) -> dict: ...
    def save_design(self, relative_path: str) -> dict: ...
    def close(self) -> None: ...
